#Subject: Signal and Image Processing
##Topic: Discrete Fourier Transform



##Aim:

a. Obtain twiddle factor matrix

b. To find the DFT and IDFT of [1,2,2,1] using twiddle factor matrix.

c. To compute the DFT using matrix method and FFT function.

d. Observe and comment on execution time required for each of the above method.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy.fft import fft, ifft
import cmath
import time

##Get twiddle factor matrix and its inverse

In [ ]:
def tw_matrix(N):                           #function to find twiddle matrix
    twiddle=np.zeros([N,N],dtype = 'complex_')
    pi=np.pi
    for i in range(N):
        for j in range(N):
            x= complex(0,-(2*pi*i*j)/N)
            y=np.exp(x)
            twiddle[i][j]=complex(round(y.real,3),round(y.imag,3))
    return twiddle

In [ ]:
N=int(input("Enter the signal size\n"))
t=tw_matrix(N)
print(t)

Enter the signal size
8
[[ 1.   -0.j     1.   -0.j     1.   -0.j     1.   -0.j     1.   -0.j
   1.   -0.j     1.   -0.j     1.   -0.j   ]
 [ 1.   -0.j     0.707-0.707j  0.   -1.j    -0.707-0.707j -1.   -0.j
  -0.707+0.707j -0.   +1.j     0.707+0.707j]
 [ 1.   -0.j     0.   -1.j    -1.   -0.j    -0.   +1.j     1.   +0.j
   0.   -1.j    -1.   -0.j    -0.   +1.j   ]
 [ 1.   -0.j    -0.707-0.707j -0.   +1.j     0.707-0.707j -1.   -0.j
   0.707+0.707j  0.   -1.j    -0.707+0.707j]
 [ 1.   -0.j    -1.   -0.j     1.   +0.j    -1.   -0.j     1.   +0.j
  -1.   -0.j     1.   +0.j    -1.   -0.j   ]
 [ 1.   -0.j    -0.707+0.707j  0.   -1.j     0.707+0.707j -1.   -0.j
   0.707-0.707j -0.   +1.j    -0.707-0.707j]
 [ 1.   -0.j    -0.   +1.j    -1.   -0.j     0.   -1.j     1.   +0.j
  -0.   +1.j    -1.   -0.j    -0.   -1.j   ]
 [ 1.   -0.j     0.707+0.707j -0.   +1.j    -0.707+0.707j -1.   -0.j
  -0.707-0.707j -0.   -1.j     0.707-0.707j]]


In [ ]:
start=time.time()
x=np.matrix([1,2,2,1])
xt=np.transpose(x)        #To be able to do matrix multiplication
t=tw_matrix(len(xt))      #Finding the twiddle matrix for the signal
X=np.transpose(t*xt)
end=time.time()
m_time=end-start
X

matrix([[ 6.+0.j, -1.-1.j,  0.+0.j, -1.+1.j]])

In [ ]:
Xt=np.transpose(X)
t=np.conj(tw_matrix(len(Xt)))     #conjugate of the twiddle matrix give the inverse twiddle matrix
x_i=np.transpose((t*Xt)/len(Xt))
x_i

matrix([[1.+0.j, 2.+0.j, 2.+0.j, 1.+0.j]])

In [ ]:
X

matrix([[ 6.+0.j, -1.-1.j,  0.+0.j, -1.+1.j]])

In [ ]:
start=time.time()
X_fft=fft(x) #result using FFT
end=time.time()
f_time=end-start
X_fft

array([[ 6.+0.j, -1.-1.j,  0.+0.j, -1.+1.j]])

In [ ]:
x_ifft=ifft(X_fft)   #result using iFFT
x_ifft

array([[1.+0.j, 2.+0.j, 2.+0.j, 1.+0.j]])

In [ ]:
m_time

0.006627082824707031

In [ ]:
f_time

0.0014476776123046875

##Conclusion:
In conclusion, the Discrete Fourier Transform (DFT) is a fundamental mathematical operation that allows us to transform a time-domain signal into its frequency-domain representation. In this Python code, we demonstrated how to use the NumPy library to implement the DFT algorithm and apply it to a signal. By computing the DFT of a signal, we were able to visualize its frequency spectrum and identify the dominant frequencies present in the signal. We also demonstrated how to apply frequency-domain filtering techniques, such as a low-pass filter, to the signal by modifying its frequency spectrum.

The DFT has many applications in signal processing, including audio and image processing, communications, and data analysis. By understanding the DFT and its implementation in Python, researchers and practitioners can leverage this powerful tool to analyze and manipulate signals for a variety of use cases.